# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  db:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=rayuki
      - MYSQL_USER=maxime
      - MYSQL_PASSWORD=pass$1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet
    command: --log_error_verbosity=2   # errors and warnings

  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    volumes:
      - /d/test/wwwroot:/app/wwwroot/apps
      - /d/test/apps:/app/apps
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=rayuki
      - MYSQL_USER=maxime
      - MYSQL_PASSWORD=pass$1234
      - MYSQL_HOST=db
      - RAYUKI_FIRSTNAME=Maxime
      - RAYUKI_LASTNAME=Betrisey
      - RAYUKI_USERNAME=maxime
      - RAYUKI_PASSWORD=pass$1234
      - LOGGING__LOGLEVEL__DEFAULT=Warning
      - LOGGING__LOGLEVEL__MICROSOFT=Warning
    networks:
      - webnet
    depends_on:
      - db
    restart: "always"

volumes:
  db_data:
networks:
  webnet:
