name: publish

on:
  push:
    branches: 
      - release

env:
  DOTNET_VERSION: '8.0.100' # The .NET SDK version to use

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Install dependencies
        run: dotnet restore   


      - name: Build
        run: |
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o ./dist -r linux-x64 --self-contained true /p:UseAppHost=true
      
      - name: Release
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: test
          artifacts: "dist"
          draft: false
          prerelease: false
